### ISSUE TITLE
Add `initial_build_id` to source configuration

### ISSUE THREAD

**Issue by jchesterpivotal** [jchesterpivotal/concourse-build-resource#18]
## Description

At the moment, the resource begins with the most recent build from the remote Concourse. But I might actually want to start with a historical version and then work forwards.

Suppose I have a Concourse with 100 builds. If I have this configuration:

```yaml
- name: build
  type: concourse-build
  source:
    concourse_url: https://concourse.example.com
```

Then the resource will start at build 100: `[{"build_id","100"}]`. 

But what I want to be able to do is start with, say, build 95:

```yaml
  source:
    concourse_url: https://concourse.example.com
    initial_build_id: 95
```

Then the resource would return `[{"build_id","95"}]` for the first invocation (ie, it would not dial out at all, but simply return the configured value). When invoked the second time it would detect the difference and return the rest: `[{"build_id","96"}, {"build_id","97"}, {"build_id","98"}, {"build_id","99"}, {"build_id","100"}]`.

## Open questions:

* What happens if that build ID doesn't exist / isn't visible?
* How do I clearly document the difference between `build_id` (the _actual_ version) and the build name / build number shown in the web UI for each individual job?

## Todos

* [x] add key
* [x] use `Since` for API paging
* [x] update readme
